// Build a honeycomb world map: rasterize Natural Earth land into a flat-top hex grid.
// Output -> src/worldHexes.ts  (baked land hex centers + projection constants)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const geo = JSON.parse(readFileSync("/tmp/ne_land.geojson", "utf8"));

// ---- Projection (equirectangular), cropped to drop most of Antarctica ----
const LON_MIN = -180, LON_MAX = 180;
const LAT_MAX = 83, LAT_MIN = -56;
const W = 760;
const H = Math.round((W * (LAT_MAX - LAT_MIN)) / (LON_MAX - LON_MIN)); // keep degrees square

const projX = (lon) => ((lon - LON_MIN) / (LON_MAX - LON_MIN)) * W;
const projY = (lat) => ((LAT_MAX - lat) / (LAT_MAX - LAT_MIN)) * H;
const invLon = (x) => LON_MIN + (x / W) * (LON_MAX - LON_MIN);
const invLat = (y) => LAT_MAX - (y / H) * (LAT_MAX - LAT_MIN);

// ---- point-in-polygon (ray cast) over lon/lat rings, honoring holes ----
function inRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1];
    const xj = ring[j][0], yj = ring[j][1];
    const hit = yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
    if (hit) inside = !inside;
  }
  return inside;
}
function inPolygon(lon, lat, rings) {
  if (!inRing(lon, lat, rings[0])) return false;
  for (let k = 1; k < rings.length; k++) if (inRing(lon, lat, rings[k])) return false; // hole
  return true;
}
// collect all polygons (each = array of rings) with a bbox for quick reject
const polys = [];
for (const f of geo.features) {
  const g = f.geometry;
  const list = g.type === "Polygon" ? [g.coordinates] : g.type === "MultiPolygon" ? g.coordinates : [];
  for (const rings of list) {
    let minx = 1e9, miny = 1e9, maxx = -1e9, maxy = -1e9;
    for (const [lo, la] of rings[0]) {
      if (lo < minx) minx = lo; if (lo > maxx) maxx = lo;
      if (la < miny) miny = la; if (la > maxy) maxy = la;
    }
    polys.push({ rings, minx, miny, maxx, maxy });
  }
}
const isLand = (lon, lat) => {
  for (const p of polys) {
    if (lon < p.minx || lon > p.maxx || lat < p.miny || lat > p.maxy) continue;
    if (inPolygon(lon, lat, p.rings)) return true;
  }
  return false;
};

// ---- flat-top hex grid over the pixel viewBox ----
const S = 6.6;                 // hex radius (px) -> controls dot density
const DX = 1.5 * S;
const DY = Math.sqrt(3) * S;

const hexes = [];
let col = 0;
for (let x = S; x <= W - S * 0.5; x += DX, col++) {
  const yOff = col % 2 ? DY / 2 : 0;
  for (let y = S + yOff; y <= H - S * 0.4; y += DY) {
    if (isLand(invLon(x), invLat(y))) hexes.push([Math.round(x * 10) / 10, Math.round(y * 10) / 10]);
  }
}

const header = `// AUTO-GENERATED by scripts/genmap.mjs — Natural Earth 110m land rasterized to a hex grid.
// Do not edit by hand; re-run \`node scripts/genmap.mjs\` to regenerate.
export const MAP_W = ${W};
export const MAP_H = ${H};
export const HEX_S = ${S};
const L = { lonMin: ${LON_MIN}, lonMax: ${LON_MAX}, latMax: ${LAT_MAX}, latMin: ${LAT_MIN} };
export const projectLonLat = (lon: number, lat: number) => ({
  x: ((lon - L.lonMin) / (L.lonMax - L.lonMin)) * MAP_W,
  y: ((L.latMax - lat) / (L.latMax - L.latMin)) * MAP_H,
});
export const HEXES: [number, number][] = ${JSON.stringify(hexes)};
`;

mkdirSync("src", { recursive: true });
writeFileSync("src/worldHexes.ts", header);
console.log(`viewBox ${W}x${H}, hexes: ${hexes.length}, cols: ${col}`);
